### ISSUE TITLE
configuring "before" and "after" hooks

### ISSUE THREAD

**Issue by atsalolikhin-spokeo** [hughbien/thyme#10]
Hi! I just installed thyme and I tried to configure it to play sounds before and after each pomodoro (let's say a ticking sound before, and a ringing sound after, like a kitchen timer).

```
hooks:
  notify:
    events: ["before"]
    command: "play ticking-sound.mp3" 

  notify:
    events: ["after"]
    command: "play ringing-sound.mp3" 

```

It would only play the ringing sound.  

After staring at the YAML for a while, I realized with this structure, the second value of notify overrides the first one; in other words, if I swap the two and put "after" first and "before" after, then I get the before sound but not the after sound.

So I used this:

```
hooks:
  notify:
    events: ["before"]
    command: ...

  notify_break:
    events: ["before_break"]
    command: ...
```

to get both sounds, but that only works if I run `thyme -r`; I can't get that with a single pomodoro.

What am I missing?  :)
